Music_Sharing_Site2/urls.py
from django.urls import path
from django.views.defaults import page_not_found
from django.contrib import admin
from django.urls import path,include
import music.urls,users.urls
from users import views as user_views
from django.conf import settings
from django.conf.urls.static import static


from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', user_views.home, name='home'),
    path('admin/', admin.site.urls),
    path('users/',include(users.urls)),
    path('music/',include(music.urls)),
    path('password-reset/',
         auth_views.PasswordResetView.as_view(
             template_name='users/password_reset.html'
         ),
         name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='users/password_reset_done.html'
         ),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='users/password_reset_confirm.html'
         ),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='users/password_reset_complete.html'
         ),
         name='password_reset_complete'),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

music/urls.py
from django.urls import path
from . import views
from django.urls import path, include

from .views import toggle

app_name = 'music'

urlpatterns = [
    # path('toggle/(<album_id>)', views.toggle, name='toggle'),
    # path('(<album_id>[0-9]+)/', views.detail, name='detail'),
    # path('(<song_id>[0-9]+)/favorite/', views.favorite, name='favorite'),
    # path('songs/(<filter_by>[a-zA_Z]+)/', views.songs, name='songs'),
    # path('create_album/', views.create_album, name='create_album'),
    # path('(<album_id>[0-9]+)/create_song/', views.create_song, name='create_song'),
    # path('(<album_id>[0-9]+)/delete_song/(<song_id>[0-9]+)/', views.delete_song, name='delete_song'),
    # path('(<album_id>[0-9]+)/favorite_album/', views.favorite_album, name='favorite_album'),
    # path('(<album_id>[0-9]+)/delete_album/', views.delete_album, name='delete_album'),
    # path('(<album_id>[0-9]+)/share_album/', views.share_album, name='share_album'),
    # path('(<album_id>[0-9]+)', views.share_album_detail, name='share_album_detail'),
    # path('share/(<album_id>[0-9]+)/(?P<username>[\w\-]+)/$', views.share, name="share"),
    # path('unshare/(<album_id>[0-9]+)/(?P<username>[\w\-]+)/$', views.unshare, name="unshare"),

    path('toggle/(<album_id>)', views.toggle, name='toggle'),
    path('(<album_id>[0-9]+)/', views.detail, name='detail'),
    path('(<song_id>[0-9]+)/favorite/', views.favorite, name='favorite'),
    path('songs/(<filter_by>[a-zA_Z]+)/', views.songs, name='songs'),
    path('create_album/', views.create_album, name='create_album'),
    path('(<album_id>[0-9]+)/create_song/', views.create_song, name='create_song'),
    path('(<album_id>[0-9]+)/delete_song/(<song_id>[0-9]+)/', views.delete_song, name='delete_song'),
    path('(<album_id>[0-9]+)/favorite_album/', views.favorite_album, name='favorite_album'),
    path('(<album_id>[0-9]+)/delete_album/', views.delete_album, name='delete_album'),
    path('(<album_id>[0-9]+)/share_album/', views.share_album, name='share_album'),
    path('(<album_id>[0-9]+)', views.share_album_detail, name='share_album_detail'),
    path('share/(<album_id>[0-9]+)/(<username>[\w\-]+)/', views.share, name="share"),
    path('unshare/(<album_id>[0-9]+)/(<username>[\w\-]+)/', views.unshare, name="unshare"),
]

music/models.py
from django.contrib.auth.models import Permission, User
from django.db import models


class Album(models.Model):
    user = models.ForeignKey(User, default=1,on_delete=models.CASCADE)
    artist = models.CharField(max_length=250)
    album_title = models.CharField(max_length=500)
    genre = models.CharField(max_length=100)
    album_logo = models.FileField(upload_to="album_logos/")
    is_favorite = models.BooleanField(default=False)
    is_private = models.BooleanField(default=True,help_text="Is this a private album ? ")
    total_songs = models.IntegerField(default=0)
    shared = models.BooleanField(default=False)

    def __str__(self):
        return self.album_title + ' - ' + self.artist


class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    song_title = models.CharField(max_length=250)
    audio_file = models.FileField(upload_to="songs/")
    is_favorite = models.BooleanField(default=False)

    def __str__(self):
        return self.song_title

class Shared_album(models.Model):
    owner = models.ForeignKey(User,on_delete=models.CASCADE,related_name='%(class)s_album_sender')
    receiver = models.ForeignKey(User, on_delete=models.CASCADE,related_name='%(class)s_album_receiver')
    album_title = models.ForeignKey(Album,on_delete=models.CASCADE)

music/forms.py
from django import forms
from django.contrib.auth.models import User
from django_toggle_switch_widget.widgets import DjangoToggleSwitchWidget

from .models import Album, Song


class AlbumForm(forms.ModelForm):
    class Meta:
        model = Album
        fields = ['artist', 'album_title', 'genre', 'album_logo','is_private']

    def __init__(self, *args, **kwargs):
        super(AlbumForm, self).__init__(*args, **kwargs)
        self.fields['is_private'].label = "Is this a private album ?"

class SongForm(forms.ModelForm):

    class Meta:
        model = Song
        fields = ['song_title', 'audio_file']

music/views.py
from itertools import chain

from django.db.models import Q
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404
from django.template.response import TemplateResponse

from users.models import Friend
from .forms import AlbumForm, SongForm
from .models import Album, Song, Shared_album
from django.contrib.auth.models import User

AUDIO_FILE_TYPES = ['wav', 'mp3', 'ogg']
IMAGE_FILE_TYPES = ['png', 'jpg', 'jpeg']


def create_album(request):
    if not request.user.is_authenticated:
        return render(request, '../templates/users/login.html')
    else:
        form = AlbumForm(request.POST or None, request.FILES or None)
        if form.is_valid():
            album = form.save(commit=False)
            album.is_private = form.cleaned_data['is_private']
            album.user = request.user
            album.album_logo = request.FILES['album_logo']
            file_type = album.album_logo.url.split('.')[-1]
            file_type = file_type.lower()
            if file_type not in IMAGE_FILE_TYPES:
                context = {
                    'album': album,
                    'form': form,
                    'error_message': 'Image file must be PNG, JPG, or JPEG',
                }
                return render(request, '../templates/music/create_album.html', context)
            album.save()
            return render(request, '../templates/music/detail.html', {'album': album})
        context = {
            "form": form,
        }
        return render(request, '../templates/music/create_album.html', context)


def create_song(request, album_id):
    form = SongForm(request.POST or None, request.FILES or None)
    album = get_object_or_404(Album, pk=album_id)
    if form.is_valid():
        albums_songs = album.song_set.all()
        for s in albums_songs:
            if s.song_title == form.cleaned_data.get("song_title"):
                context = {
                    'album': album,
                    'form': form,
                    'error_message': 'You already added that song',
                }
                return render(request, '../templates/music/create_song.html', context)
        song = form.save(commit=False)
        song.album = album
        song.audio_file = request.FILES['audio_file']
        file_type = song.audio_file.url.split('.')[-1]
        file_type = file_type.lower()
        if file_type not in AUDIO_FILE_TYPES:
            context = {
                'album': album,
                'form': form,
                'error_message': 'Audio file must be WAV, MP3, or OGG',
            }
            return render(request, '../templates/music/create_song.html', context)
        album.total_songs = album.total_songs + 1
        album.save()
        song.save()
        return render(request, '../templates/music/detail.html', {'album': album})
    context = {
        'album': album,
        'form': form,
    }
    return render(request, '../templates/music/create_song.html', context)


def delete_album(request, album_id):
    album = Album.objects.get(pk=album_id)
    album.delete()
    albums = Album.objects.filter(user=request.user)
    followee = Friend.objects.filter(follower=request.user)
    friends_albums = []
    for follo in followee:
        x = Album.objects.filter(Q(user=follo.followee)).exclude(is_private=True)
        friends_albums = chain(friends_albums, x)

    received_albums = Shared_album.objects.filter(receiver=request.user)
    public_albums = Album.objects.exclude(user=request.user).filter(is_private=False)
    context = {
        'albums': albums,  # unique albums
        'received_albums': received_albums,
        'public_albums': public_albums,
        'friends_albums': friends_albums
    }
    return render(request, 'users/index.html', context)


def delete_song(request, album_id, song_id):
    album = get_object_or_404(Album, pk=album_id)
    song = Song.objects.get(pk=song_id)
    album.total_songs -= 1
    album.save()
    song.delete()
    return render(request, '../templates/music/detail.html', {'album': album})


def detail(request, album_id):
    if not request.user.is_authenticated:
        return render(request, '../templates/users/login.html')
    else:
        user = request.user
        album = get_object_or_404(Album, pk=album_id)
        return render(request, '../templates/music/detail.html', {'album': album, 'user': user})


def favorite(request, song_id):
    song = get_object_or_404(Song, pk=song_id)
    try:
        if song.is_favorite:
            song.is_favorite = False
        else:
            song.is_favorite = True
        song.save()
    except (KeyError, Song.DoesNotExist):
        return JsonResponse({'success': False})
    else:
        return JsonResponse({'success': True})


def favorite_album(request, album_id):
    album = get_object_or_404(Album, pk=album_id)
    try:
        if album.is_favorite:
            album.is_favorite = False
        else:
            album.is_favorite = True
        album.save()
    except (KeyError, Album.DoesNotExist):
        return JsonResponse({'success': False})
    else:
        return JsonResponse({'success': True})


def songs(request, filter_by):
    if not request.user.is_authenticated:
        return render(request, '../templates/users/login.html')
    else:
        try:
            song_ids = []
            for album in Album.objects.filter(user=request.user):
                for song in album.song_set.all():
                    song_ids.append(song.pk)
            users_songs = Song.objects.filter(pk__in=song_ids)
            if filter_by == 'favorites':
                users_songs = users_songs.filter(is_favorite=True)
        except Album.DoesNotExist:
            users_songs = []
        return render(request, '../templates/music/songs.html', {
            'song_list': users_songs,
            'filter_by': filter_by,
        })

def toggle(request,album_id):
    print("inside toggle")
    w = get_object_or_404(Album, pk=album_id)
    w.is_private = not w.is_private
    w.save()
    user = request.user
    album = get_object_or_404(Album, pk=album_id)
    return render(request, '../templates/music/detail.html', {'album': album, 'user': user})


def share_album(request, album_id):
    album = get_object_or_404(Album,pk=album_id)
    already_shared_users = Shared_album.objects.filter(album_title=album)
    all_users_objects = User.objects.exclude(username=request.user.username)
    
    all_users = []
    for u in all_users_objects:
        all_users.append(u.username)

    shared_users_list = []
    for u in already_shared_users:
        shared_users_list.append(u.receiver.username)

    unshared_users = list(set(all_users) - set(shared_users_list))

    context = {
        "shared_users": shared_users_list,
        "unshared_users":unshared_users,
        "album_id": album_id
    }
    return render(request,'../templates/music/share_album.html',context)

def share_album_detail(request, album_id):
    if not request.user.is_authenticated:
        return render(request, '../templates/users/login.html')
    else:
        user = request.user
        album = get_object_or_404(Album, pk=album_id)
        return render(request, '../templates/music/shared_album_detail.html', {'album': album, 'user': user})


def share(request,album_id,username):
    album = get_object_or_404(Album,pk=album_id)
    receiver = get_object_or_404(User,username=username)
    Shared_album.objects.create(owner=request.user,receiver=receiver,album_title=album)
    return share_album(request,album_id)

def unshare(request,album_id,username):
    album = Shared_album.objects.filter(receiver__username=username,album_title=get_object_or_404(Album,pk=album_id))
    print(album)
    album.delete()
    return share_album(request,album_id)

templates/music/create_song.html
{% extends 'base.html' %}
{% block title %}Add a New Song{% endblock %}
{% block albums_active %}active{% endblock %}

{% block body %}
    <br><br>
<div class="container-fluid">

    <div class="row">

        <!-- Left Album Info -->
        <div class="col-sm-4 col-md-3">
            <div class="panel panel-default">
                <div class="panel-body">
                        <a href="{% url 'music:detail' album.id %}">
                            {% if album.album_logo %}
                                <img src="{{ album.album_logo.url }}" class="img-responsive">
                            {% else %}
                                <h3>No image to display</h3>
                            {% endif %}
                        </a>
                    <h1>{{ album.album_title }} <small>{{ album.genre }}</small></h1>
                    <h2>{{ album.artist }}</h2>
                </div>
            </div>
        </div>

        <!-- Right Song Info -->
        <div class="col-sm-8 col-md-9">

            <ul class="nav nav-pills" style="margin-bottom: 10px;">
                <li role="presentation"><a href="{% url 'music:detail' album.id %}">View All</a></li>
                <li role="presentation" class="active"><a href="{% url 'music:create_song' album.id %}">Add New Song</a></li>
            </ul>

            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Add a New Song</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <input type="hidden" name="album" value="{{ album }}">
                        {% include 'music/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>

        </div>

    </div>

</div>

{% endblock %}

templates/music/detail.html
{% extends 'base.html' %}

{% load static %}
{% block myscss %}

    <style>
        .switch {
            position: relative;
            display: inline-block;
            width: 60px;
            height: 34px;
        }

        /* Hide default HTML checkbox */
        .switch input {
            opacity: 0;
            width: 0;
            height: 0;
        }

        /* The slider */
        .slider {
            position: absolute;
            cursor: pointer;
            top: 0;
            left: 0;
            right: 0;
            bottom: 0;
            background-color: #ccc;
            -webkit-transition: .4s;
            transition: .4s;
        }

        .slider:before {
            position: absolute;
            content: "";
            height: 26px;
            width: 26px;
            left: 4px;
            bottom: 4px;
            background-color: white;
            -webkit-transition: .4s;
            transition: .4s;
        }

        input:checked + .slider {
            background-color: #2196F3;
        }

        input:focus + .slider {
            box-shadow: 0 0 1px #2196F3;
        }

        input:checked + .slider:before {
            -webkit-transform: translateX(26px);
            -ms-transform: translateX(26px);
            transform: translateX(26px);
        }

        /* Rounded sliders */
        .slider.round {
            border-radius: 34px;
        }

        .slider.round:before {
            border-radius: 50%;
        }
    </style>

{% endblock %}

{% block title %}{{ album }}{% endblock %}
{% block albums_active %}active{% endblock %}


{% block body %}
    <br><br>
    <div class="container-fluid songs-container">

        <div class="row">

            <!-- Left Album Info -->
            <div class="col-sm-4 col-md-3">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <a href="{% url 'music:detail' album.id %}">
                            {% if album.album_logo %}
                                <img src="{{ album.album_logo.url }}" class="img-responsive">
                            {% else %}
                                <h3>No image to display</h3>
                            {% endif %}
                        </a>
                        <h1>{{ album.album_title }} <small>{{ album.genre }}</small></h1>
                        <h2>{{ album.artist }}</h2>
                    </div>
                </div>
            </div>

            <!-- Right Song Info -->
            <div class="col-sm-8 col-md-9">

                <ul class="nav nav-pills" style="margin-bottom: 10px;">
                    <li role="presentation" class="active"><a href="{% url 'music:detail' album.id %}">View All</a></li>
                    <li role="presentation"><a href="{% url 'music:create_song' album.id %}">Add New Song</a></li>
                    <pre class="col-sm-4 col-md-4"><li role="presentation"><h4>            Total songs : {{ album.total_songs }}</h4></li></pre>
                    <div class="col-md-2"><li >
                        <label>Is this a private album ?</label>
                        {% if album.is_private %}
                            <label class="switch col-md-offset-4">
                            <input data-href="{% url 'music:toggle' album.id %}" type="checkbox" id="checkbox" checked onclick="myFunction()">
                            <span class="slider round"></span>
                            </label>
                        {% else %}
                            <label class="switch">
                            <input data-href="{% url 'music:toggle' album.id %}" type="checkbox" id="checkbox" value="{{ album.is_private }}" onclick="myFunction()">
                            <span class="slider round"></span>
                            </label>
                        {% endif %}
                    </li>
                    </div>
                </ul>

                <div class="panel panel-default">
                    <div class="panel-body">

                        <h3>All Songs</h3>

                        {% if error_message %}
                            <p><strong>{{ error_message }}</strong></p>
                        {% endif %}

                        <table class="table">
                            <thead>
                            <tr>
                                <th>Title</th>
                                <th>Audio File</th>
                                <th>Favorite</th>
                                <th>Actions</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for song in album.song_set.all %}
                                <tr>
                                    <td>{{ song.song_title }}</td>
                                    <td>
                                        <a target="_blank" href="{{ song.audio_file.url }}">
                                            <button type="button" class="btn btn-success btn-xs">
                                                <span class="glyphicon glyphicon-play"></span>&nbsp; Play
                                            </button>
                                        </a>
                                    </td>
                                    <td>
                                        <a href="{% url 'music:favorite' song.id %}" class="btn-favorite"><span
                                                class="glyphicon glyphicon-star {% if song.is_favorite %}active{% endif %}"></span></a>
                                    </td>
                                    <td>
                                        <form action="{% url 'music:delete_song' album.id song.id %}" method="post"
                                              style="display: inline;">
                                            {% csrf_token %}
                                            <input type="hidden" name="song_id" value="{{ song.id }}"/>
                                            <button type="submit" class="btn btn-danger btn-xs">
                                                <span class="glyphicon glyphicon-remove"></span>&nbsp; Delete
                                            </button>
                                        </form>
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>

                    </div>
                </div>

            </div>

        </div>

    </div>

{% endblock %}

templates/music/form_template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2" for="song_title">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

templates/music/share_album.html
{% extends 'base.html' %}
{% block title %}Log In{% endblock %}
{% block login_active %}active{% endblock %}

{% block body %}
    <br><br>
    <div class="panel panel-default">
        <div class="panel-body">
            <table class="table">
                <thead>
                <tr>
                    <th>
                        <h3>Users</h3>
                    </th>
                </tr>
                </thead>
                <tbody>

                {% if not unshared_users %}
                    <tr>

                        <td>
                            <h4>
                                You have Shared it with all the users.
                            </h4>
                        </td>

                    </tr>
                {% endif %}

                {% for unshared_user in unshared_users %}
                    <tr>

                        <td>
                            {{ unshared_user }}
                            <a href="{% url 'music:share' album_id unshared_user %}">Share</a>
                        </td>

                    </tr>

                {% endfor %}

                </tbody>
            </table>

        </div>
    </div>

    <div class="panel panel-default">
        <div class="panel-body">
            <table class="table">
                <thead>
                <tr>
                    <th>
                        <h3>Already Shared Users</h3>
                    </th>
                </tr>
                </thead>
                <tbody>
                {% if not shared_users %}
                    <tr>

                        <td>
                            <h4>
                                You haven't shared this album with any user.
                            </h4>
                        </td>

                    </tr>
                {% endif %}
                {% for shared_user in shared_users %}
                    <tr>

                        <td>
                            {{ shared_user }}
                            <a href="{% url 'music:unshare' album_id shared_user %}">Unshare</a>
                        </td>

                    </tr>

                {% endfor %}
                </tbody>
            </table>

        </div>
    </div>

{% endblock %}

templates/music/shared_album_detail.html
{% extends 'base.html' %}

{% block title %}{{ album }}{% endblock %}
{% block albums_active %}active{% endblock %}


{% block body %}
<br><br>
    <div class="container-fluid songs-container">

        <div class="row">

            <!-- Left Album Info -->
            <div class="col-sm-4 col-md-3">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <a href="{% url 'music:share_album_detail' album.id %}">
                            {% if album.album_logo %}
                                <img src="{{ album.album_logo.url }}" class="img-responsive">
                            {% else %}
                                <h3>No image to display</h3>
                            {% endif %}
                        </a>
                        <h1>{{ album.album_title }} <small>{{ album.genre }}</small></h1>
                        <h2>{{ album.artist }}</h2>
                    </div>
                </div>
            </div>

            <!-- Right Song Info -->
            <div class="col-sm-8 col-md-9">

                <ul class="nav nav-pills" style="margin-bottom: 10px;">
                    <li role="presentation" class="active"><a href="{% url 'music:share_album_detail' album.id %}">View All</a></li>

                    <li style="padding-left: 20px"> <h3>            </h3> </li>

                    <pre class="col-sm-4 col-md-4"><li role="presentation"><h4>            Total songs : {{ album.total_songs }}</h4></li></pre>
                </ul>

                <div class="panel panel-default">
                    <div class="panel-body">

                        <h3>All Songs</h3>

                        {% if error_message %}
                            <p><strong>{{ error_message }}</strong></p>
                        {% endif %}

                        <table class="table">
                            <thead>
                            <tr>
                                <th>Title</th>
                                <th>Audio File</th>
                                <th>Favorite</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for song in album.song_set.all %}
                                <tr>
                                    <td>{{ song.song_title }}</td>
                                    <td>
                                        <a target="_blank" href="{{ song.audio_file.url }}">
                                            <button type="button" class="btn btn-success btn-xs">
                                                <span class="glyphicon glyphicon-play"></span>&nbsp; Play
                                            </button>
                                        </a>
                                    </td>
                                    <td>
                                        <a href="{% url 'music:favorite' song.id %}" class="btn-favorite"><span
                                                class="glyphicon glyphicon-star {% if song.is_favorite %}active{% endif %}"></span></a>
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>

                    </div>
                </div>

            </div>

        </div>

    </div>

{% endblock %}

templates/music/songs.html
{% extends 'base.html' %}
{% block title %}All Songs{% endblock %}
{% block songs_active %}active{% endblock %}

{% block body %}
     <br><br>
<div class="container-fluid songs-container">

    <div class="row">
        <div class="col-sm-12">
            <ul class="nav nav-pills" style="margin-bottom: 10px;">

                <li role="presentation" {% if filter_by == 'all' %}class="active"{% endif %}><a href="{% url 'music:songs' 'all' %}">View All</a></li>
                <li role="presentation" {% if filter_by == 'favorites' %}class="active"{% endif %}><a href="{% url 'music:songs' 'favorites' %}">Favorites</a></li>
            </ul>
        </div>
    </div>

    <div class="row">

        <div class="col-sm-12">

            <div class="panel panel-default">
                <div class="panel-body">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>Song Title</th>
                                <th>Artist</th>
                                <th>Audio File</th>
                                <th>Album</th>
                                <th>Favorite</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for song in song_list %}
                                <tr>
                                    <td>{{ song.song_title }}</td>
                                    <td>{{ song.album.artist }}</td>
                                    <td>
                                        <a target="_blank" href="{{ song.audio_file.url }}">
                                            <button type="button" class="btn btn-success btn-xs">
                                                <span class="glyphicon glyphicon-play"></span>&nbsp; Play
                                            </button>
                                        </a>
                                    </td>
                                    <td>
                                        <a href="{% url 'music:detail' song.album.id %}">
                                            <img src="{{ song.album.album_logo.url }}" class="img-responsive" style="width: 20px; float: left; margin-right: 10px;" />
                                        </a>
                                        <a href="{% url 'music:detail' song.album.id %}">{{ song.album.album_title }}</a>
                                    </td>
                                    <td>
                                        <a href="{% url 'music:favorite' song.id %}" class="btn-favorite"><span class="glyphicon glyphicon-star {% if song.is_favorite %}active{% endif %}"></span></a>
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>

        </div>

    </div>

</div>
{% endblock %}