Music_Sharing_Site2/urls.py
from django.urls import path
from django.views.defaults import page_not_found
from django.contrib import admin
from django.urls import path,include
import music.urls,users.urls
from users import views as user_views
from django.conf import settings
from django.conf.urls.static import static


from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', user_views.home, name='home'),
    path('admin/', admin.site.urls),
    path('users/',include(users.urls)),
    path('music/',include(music.urls)),
    path('password-reset/',
         auth_views.PasswordResetView.as_view(
             template_name='users/password_reset.html'
         ),
         name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='users/password_reset_done.html'
         ),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='users/password_reset_confirm.html'
         ),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='users/password_reset_complete.html'
         ),
         name='password_reset_complete'),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

music/urls.py
from django.urls import path
from . import views
from django.urls import path, include

from .views import toggle

app_name = 'music'

urlpatterns = [
    # path('toggle/(<album_id>)', views.toggle, name='toggle'),
    # path('(<album_id>[0-9]+)/', views.detail, name='detail'),
    # path('(<song_id>[0-9]+)/favorite/', views.favorite, name='favorite'),
    # path('songs/(<filter_by>[a-zA_Z]+)/', views.songs, name='songs'),
    # path('create_album/', views.create_album, name='create_album'),
    # path('(<album_id>[0-9]+)/create_song/', views.create_song, name='create_song'),
    # path('(<album_id>[0-9]+)/delete_song/(<song_id>[0-9]+)/', views.delete_song, name='delete_song'),
    # path('(<album_id>[0-9]+)/favorite_album/', views.favorite_album, name='favorite_album'),
    # path('(<album_id>[0-9]+)/delete_album/', views.delete_album, name='delete_album'),
    # path('(<album_id>[0-9]+)/share_album/', views.share_album, name='share_album'),
    # path('(<album_id>[0-9]+)', views.share_album_detail, name='share_album_detail'),
    # path('share/(<album_id>[0-9]+)/(?P<username>[\w\-]+)/$', views.share, name="share"),
    # path('unshare/(<album_id>[0-9]+)/(?P<username>[\w\-]+)/$', views.unshare, name="unshare"),

    path('toggle/(<album_id>)', views.toggle, name='toggle'),
    path('(<album_id>[0-9]+)/', views.detail, name='detail'),
    path('(<song_id>[0-9]+)/favorite/', views.favorite, name='favorite'),
    path('songs/(<filter_by>[a-zA_Z]+)/', views.songs, name='songs'),
    path('create_album/', views.create_album, name='create_album'),
    path('(<album_id>[0-9]+)/create_song/', views.create_song, name='create_song'),
    path('(<album_id>[0-9]+)/delete_song/(<song_id>[0-9]+)/', views.delete_song, name='delete_song'),
    path('(<album_id>[0-9]+)/favorite_album/', views.favorite_album, name='favorite_album'),
    path('(<album_id>[0-9]+)/delete_album/', views.delete_album, name='delete_album'),
    path('(<album_id>[0-9]+)/share_album/', views.share_album, name='share_album'),
    path('(<album_id>[0-9]+)', views.share_album_detail, name='share_album_detail'),
    path('share/(<album_id>[0-9]+)/(<username>[\w\-]+)/', views.share, name="share"),
    path('unshare/(<album_id>[0-9]+)/(<username>[\w\-]+)/', views.unshare, name="unshare"),
]

users/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path,include

from . import views

app_name = 'users'

urlpatterns = [
    # path('index/', views.index, name='index'),
    # path('register/', views.register, name='register'),
    # path('login_user/', views.login_user, name='login_user'),
    # path('logout_user/', views.logout_user, name='logout_user'),
    # path('profile/', views.profile, name="profile"),
    # path('edit_profile/', views.edit_profile, name="edit_profile"),
    # path('update_profile/', views.update_profile, name="update_profile"),
    # path('logout/', views.logout, name="logout"),
    # path('follow_users/', views.follow_users, name="follow_users"),
    # path('follow/(?P<followee_id>\d+)/', views.follow, name="follow"),
    # path('unfollow/(?P<followee_id>\d+)/', views.unfollow, name="unfollow"),
    # path('my_followers/', views.my_followers, name="my_followers"),
    # path('follower_profile/(?P<follower_id>\d+)/', views.follower_profile, name="follower_profile")

    path('index/', views.index, name='index'),
    path('register/', views.register, name='register'),
    path('login_user/', views.login_user, name='login_user'),
    path('logout_user/', views.logout_user, name='logout_user'),
    path('profile/', views.profile, name="profile"),
    path('edit_profile/', views.edit_profile, name="edit_profile"),
    path('update_profile/', views.update_profile, name="update_profile"),
    path('logout/', views.logout, name="logout"),
    path('follow_users/', views.follow_users, name="follow_users"),
    path('follow/(<followee_id>)/', views.follow, name="follow"),
    path('unfollow/(<followee_id>)/', views.unfollow, name="unfollow"),
    path('my_followers/', views.my_followers, name="my_followers"),
    path('follower_profile/(<follower_id>)/', views.follower_profile, name="follower_profile")
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}My music{% endblock %}</title>
    {% load static %}
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.js"></script>
    <script type="text/javascript">

        $(document).ready(function myFunction() {
            $('#checkbox').change(function () {
                $.ajax( {
                    url: $(this).attr("data-href"),
                    csrfmiddlewaretoken: '{{ csrf_token }}'
                })
            })
        })

    </script>

    {% block myscss %} {% endblock %}

    <script src="{% static 'music/js/main.js' %}"></script>
</head>
<body>
{#<nav class="navbar navbar-inverse">#}
<header class="header-section clearfix header-blue">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'home' %}" class="span-visitor" style="color: white">ED YODA Music</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse header-section" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="{% block albums_active %}{% endblock %}"><a href="{% url 'users:index' %}" class="span-visitor"><span
                        class="glyphicon glyphicon-cd span-visitor" aria-hidden="true"></span>&nbsp; Albums</a></li>
                <li class="{% block songs_active %}{% endblock %}"><a href="{% url 'music:songs' 'all' %}" class="span-visitor"><span
                        class="glyphicon glyphicon-music span-visitor" aria-hidden="true"></span>&nbsp; Songs</a></li>
            </ul>
            <form class="navbar-form navbar-left" role="search" method="get" action="{% url 'users:index' %}">
                <div class="form-group">
                    <input type="text" class="form-control" name="q" value="{{ request.GET.q }}">
                </div>
                <button type="submit" class="btn btn-default">Search</button>
            </form>
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a href="{% url 'music:create_album' %}" class="span-visitor">
                        <span class="span-visitor glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add Album
                    </a>
                </li>
                <li>
                    <a href="{% url 'users:follow_users' %}" class="span-visitor">
                        <span class="span-visitor glyphicon glyphicon-heart" aria-hidden="true"></span>&nbsp; Follow People
                    </a>
                </li>
                <li>
                    <a href="{% url 'users:profile' %}" class="span-visitor">
                        <span class="glyphicon span-visitor glyphicon-user" aria-hidden="true"></span>&nbsp; My Profile
                    </a>
                </li>
                <li>
                    <a href="{% url 'users:logout_user' %}" class="span-visitor">
                        <span class="glyphicon glyphicon-off span-visitor" aria-hidden="true"></span>&nbsp; Logout
                    </a>
                </li>
            </ul>
        </div>

    </div>
{#</nav>#}
</header>
{% block body %}
{% endblock %}
</body>
</html>

templates/base_visitor.html
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}My music{% endblock %}</title>
    {% load static %}
    <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script src="{% static 'music/js/main.js' %}"></script>
</head>
<body>
{#<nav class="navbar navbar-inverse">#}
<header class="header-section clearfix header-blue">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'home' %}" style="color: white">ED YODA Music</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="{% block register_active %}{% endblock %}"><a href="{% url 'users:register' %}" class="span-visitor">Register</a></li>
                <li class="{% block login_active %}{% endblock %}"><a href="{% url 'users:login_user' %}" class="span-visitor">Log In</a></li>
            </ul>
        </div>

    </div>
</header>
        {% if messages %}
            {% for message in messages %}
              <div class="alert alert-{{ message.tags }}">
                {{ message }}
              </div>
            {% endfor %}
          {% endif %}
          {% block content %}{% endblock content%}
</body>
</html>

templates/base_visitor2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}My music{% endblock %}</title>
    {% load static %}
    <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script src="{% static 'music/js/main.js' %}"></script>
</head>
<body>
{#<nav class="navbar navbar-inverse">#}
<header class="header-section clearfix header-blue">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'home' %}" class="span-visitor" style="color: white">ED YODA Music</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="{% block register_active %}{% endblock %}"><a href="{% url 'users:register' %}" class="span-visitor">Register</a></li>
                <li class="{% block login_active %}{% endblock %}"><a href="{% url 'users:login_user' %}" class="span-visitor">Log In</a></li>
            </ul>
        </div>

    </div>
{#</nav>#}
</header>
{% block body%}
{% endblock body %}
</body>
</html>

templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
	<title>{% block title %}ED YODA Music{% endblock %}</title>
    {% load static %}
	<meta charset="UTF-8">
	<meta name="description" content="CTK-Music Template">
	<meta name="keywords" content="music, html">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	
	<!-- Favicon -->
	<link href="{% static 'favicon.ico' %}" rel="shortcut icon"/>

	<!-- Google font -->
	<link href="https://fonts.googleapis.com/css?family=Montserrat:300,300i,400,400i,500,500i,600,600i,700,700i&display=swap" rel="stylesheet">
 
	<!-- Stylesheets -->
	<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"/>
	<link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}"/>
	<link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}"/>
	<link rel="stylesheet" href="{% static 'css/slicknav.min.css' %}"/>

	<!-- Main Stylesheets -->
	<link rel="stylesheet" href="{% static 'css/style.css' %}"/>

</head>
<body>
{% block body %}
	<!-- Page Preloder -->
	<div id="preloder">
		<div class="loader"></div>
	</div>

	<!-- Header section -->
	<header class="header-section clearfix">
		{% comment %} <a href="{% url 'home' %}" class="site-logo">
			<img src="../static/img/h-logo.png" alt="">
		</a> {% endcomment %}
		<div class="header-right">
			<div class="user-panel">
				<a href="{% url 'users:index' %}" class="login">Login</a>
				<a href="{% url 'users:register' %}" class="register">Create an account</a>
			</div> 
		</div>
		<ul class="main-menu">
		</ul>
	</header>
	<!-- Header section end -->

	<!-- Hero section -->
	<section class="hero-section">
		<div class="hero-slider owl-carousel">
			<div class="hs-item">
				<div class="container">
					<div class="row">
						<div class="col-lg-6">
							<div class="hs-text">
								<h2><span>Music</span> for everyone.</h2>
								<p>Without music life would be a mistake, Join us today.</p>
								<a href="{% url 'users:index' %}" class="site-btn">SignIn Here</a>
								<a href="{% url 'users:register' %}" class="site-btn sb-c2">New Member ? SignUp</a>
							</div>
						</div>
						<div class="col-lg-6">
							<div class="hr-img">
								<img src="{% static 'img/hero-bg.png' %}" alt="">
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="hs-item">
				<div class="container">
					<div class="row">
						<div class="col-lg-6">
							<div class="hs-text">
								<h2><span>Listen & Share </span> to new music.</h2>
								<p>Where words fail, music speaks.</p>
								<a href="{% url 'users:index' %}" class="site-btn">SignIn Here</a>
								<a href="{% url 'users:register' %}" class="site-btn sb-c2">New Member ? SignUp</a>
							</div>
						</div>
						<div class="col-lg-6">
							<div class="hr-img">
								<img src="{% static 'img/hero-bg.png' %}" alt="">
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>
	<!-- Hero section end -->

	<!-- Intro section -->
	<section class="intro-section spad">
		<div class="container">
			<div class="row">
				<div class="col-lg-6">
					<div class="section-title">
						<h2>Unlimited Access to 100K tracks</h2>
					</div>
				</div>
				<div class="col-lg-6">
					<p>ED YODA Music is the world’s leading music and audio discovery platform. Whether you’re an artist, podcaster, or label; get the tools you need to share your music and grow with us.</p>
					<a href="{% url 'users:index' %}" class="site-btn">Try it now</a>
				</div>
			</div>
		</div>
	</section>
	<!-- Intro section end -->

	<!-- How section -->
	<section class="how-section spad set-bg" data-setbg="{% static 'img/how-to-bg.jpg' %}">
		<div class="container text-white">
			<div class="section-title">
				<h2>How it works</h2>
			</div>
			<div class="row">
				<div class="col-md-4">
					<div class="how-item">
						<div class="hi-icon">
							<img src="{% static 'img/icons/brain.png' %}" alt="">
						</div>
						<h4>Join US</h4>
						<p>ED YODA Music is the world’s leading music and audio discovery platform. Whether you’re an artist, podcaster, or label; get the tools you need to share your music and grow your audience. </p>
					</div>
				</div>
				<div class="col-md-4">
					<div class="how-item">
						<div class="hi-icon">
							<img src="{% static 'img/icons/pointer.png' %}" alt="">
						</div>
						<h4>Unique Features</h4>
						<p>Being a member you will be given a chance to share your music with the world.You can have PRIVATE,PUBLIC & SHARED 3 types of albums.You even can follow your favourite users. </p>
					</div>
				</div>
				<div class="col-md-4">
					<div class="how-item">
						<div class="hi-icon">
							<img src="{% static 'img/icons/smartphone.png' %}" alt="">
						</div>
						<h4>Play Music</h4>
						<p>Listen to your favourite music.Free access to Millions of songs. No credit card needed.</p>
					</div>
				</div>
			</div>
		</div>
	</section>
	<!-- How section end -->

	<!-- Premium section end -->
	<section class="premium-section spad">
		<div class="container">
			<div class="row">
				<div class="col-lg-6">
					<div class="section-title">
						<h2>Top Features</h2>
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col-lg-3 col-sm-6">
					<div class="premium-item">
						<img src="{% static 'img/premium/1.jpg' %}" alt="">
						<h4>No interruptions </h4>
					</div>
				</div>
				<div class="col-lg-3 col-sm-6">
					<div class="premium-item">
						<img src="{% static 'img/premium/2.jpg' %}" alt="">
						<h4>High Quality</h4>
					</div>
				</div>
				<div class="col-lg-3 col-sm-6">
					<div class="premium-item">
						<img src="{% static 'img/premium/3.jpg' %}" alt="">
						<h4>24/7 music</h4>
					</div>
				</div>
				<div class="col-lg-3 col-sm-6">
					<div class="premium-item">
						<img src="{% static 'img/premium/4.jpg' %}" alt="">
						<h4>Volume Control</h4>
					</div>
				</div>
			</div>
		</div>
	</section>
	<!-- Premium section end -->

	<!-- Concept section -->
	<section class="concept-section spad">
		<div class="container">
			<div class="row">
				<div class="col-lg-6">
					<div class="section-title">
						<h2>Write For ED YODA Music</h2>
					</div>
				</div>
				<a href="mailto:example@gmail.com?subject=Feedback" class="site-btn"><h3 style="color: white">Feel free to write down anything you want.</h3></a>
			</div>
		</div>
	</section>
	<!-- Concept section end -->

	<!-- Subscription section -->
	<section class="subscription-section spad">
		<div class="container">
			<div class="row">
				<div class="col-lg-6">
					<div class="sub-text">
						<h2>Contact Us</h2>
						<h3>Email :- </h3>
						<p>example@gmail.com</p>
						<br>
						<h3>Phone :-</h3>
						<p>+91-987654321</p>
						<a href="#" class="site-btn">Try It Now</a>
					</div>
				</div>
				<div class="col-lg-6">
					<ul class="sub-list">
						<li><img src="{% static 'img/icons/check-icon.png' %}" alt="">Play any track</li>
						<li><img src="{% static 'img/icons/check-icon.png' %}" alt="">24/7 online</li>
						<li><img src="{% static 'img/icons/check-icon.png' %}" alt="">No interruptions</li>
						<li><img src="{% static 'img/icons/check-icon.png' %}" alt="">Unlimited skips</li>
						<li><img src="{% static 'img/icons/check-icon.png' %}" alt="">High quality audio</li>
						<li><img src="{% static 'img/icons/check-icon.png' %}" alt="">Shuffle play</li>
					</ul>
				</div>
			</div>
		</div>
	</section>
	<!-- Subscription section end -->

	<!-- Footer section -->
	<footer class="footer-section">
		<div class="container">
			<div class="row">
				<div class="col-xl-6 col-lg-7 order-lg-2">
					<div class="row">
						<div class="col-sm-4">
							<div class="footer-widget">
							</div>
						</div>
						<div class="col-sm-4">
							<div class="footer-widget">
							</div>
						</div>
						<div class="col-sm-4">
							<div class="footer-widget">
							</div>
						</div>
					</div>
				</div>
				<div class="col-xl-6 col-lg-5 order-lg-1">
					{% comment %} <img src="{% static 'img/h-logo.png' %}" alt=""> {% endcomment %}
					<div class="copyright">
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This Site is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a>ED YODA Music</a>
</div>
					<div class="social-links">
						<a href="https://www.instagram.com" target="__blank"><i class="fa fa-instagram"></i></a>
						<a href="https://www.facebook.com" target="__blank"><i class="fa fa-facebook"></i></a>
					</div>
				</div>
			</div>
		</div>
	</footer>
	<!-- Footer section end -->
	
	<!--====== Javascripts & Jquery ======-->
	<script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
	<script src="{% static 'js/bootstrap.min.js' %}"></script>
	<script src="{% static 'js/jquery.slicknav.min.js' %}"></script>
	<script src="{% static 'js/owl.carousel.min.js' %}"></script>
	<script src="{% static 'js/mixitup.min.js' %}"></script>
	<script src="{% static 'js/main.js' %}"></script>

{% endblock %}
	</body>
</html>