Music_Sharing_Site2/urls.py
from django.urls import path
from django.views.defaults import page_not_found
from django.contrib import admin
from django.urls import path,include
import music.urls,users.urls
from users import views as user_views
from django.conf import settings
from django.conf.urls.static import static


from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', user_views.home, name='home'),
    path('admin/', admin.site.urls),
    path('users/',include(users.urls)),
    path('music/',include(music.urls)),
    path('password-reset/',
         auth_views.PasswordResetView.as_view(
             template_name='users/password_reset.html'
         ),
         name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='users/password_reset_done.html'
         ),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='users/password_reset_confirm.html'
         ),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='users/password_reset_complete.html'
         ),
         name='password_reset_complete'),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

music/urls.py
from django.urls import path
from . import views
from django.urls import path, include

from .views import toggle

app_name = 'music'

urlpatterns = [
    # path('toggle/(<album_id>)', views.toggle, name='toggle'),
    # path('(<album_id>[0-9]+)/', views.detail, name='detail'),
    # path('(<song_id>[0-9]+)/favorite/', views.favorite, name='favorite'),
    # path('songs/(<filter_by>[a-zA_Z]+)/', views.songs, name='songs'),
    # path('create_album/', views.create_album, name='create_album'),
    # path('(<album_id>[0-9]+)/create_song/', views.create_song, name='create_song'),
    # path('(<album_id>[0-9]+)/delete_song/(<song_id>[0-9]+)/', views.delete_song, name='delete_song'),
    # path('(<album_id>[0-9]+)/favorite_album/', views.favorite_album, name='favorite_album'),
    # path('(<album_id>[0-9]+)/delete_album/', views.delete_album, name='delete_album'),
    # path('(<album_id>[0-9]+)/share_album/', views.share_album, name='share_album'),
    # path('(<album_id>[0-9]+)', views.share_album_detail, name='share_album_detail'),
    # path('share/(<album_id>[0-9]+)/(?P<username>[\w\-]+)/$', views.share, name="share"),
    # path('unshare/(<album_id>[0-9]+)/(?P<username>[\w\-]+)/$', views.unshare, name="unshare"),

    path('toggle/(<album_id>)', views.toggle, name='toggle'),
    path('(<album_id>[0-9]+)/', views.detail, name='detail'),
    path('(<song_id>[0-9]+)/favorite/', views.favorite, name='favorite'),
    path('songs/(<filter_by>[a-zA_Z]+)/', views.songs, name='songs'),
    path('create_album/', views.create_album, name='create_album'),
    path('(<album_id>[0-9]+)/create_song/', views.create_song, name='create_song'),
    path('(<album_id>[0-9]+)/delete_song/(<song_id>[0-9]+)/', views.delete_song, name='delete_song'),
    path('(<album_id>[0-9]+)/favorite_album/', views.favorite_album, name='favorite_album'),
    path('(<album_id>[0-9]+)/delete_album/', views.delete_album, name='delete_album'),
    path('(<album_id>[0-9]+)/share_album/', views.share_album, name='share_album'),
    path('(<album_id>[0-9]+)', views.share_album_detail, name='share_album_detail'),
    path('share/(<album_id>[0-9]+)/(<username>[\w\-]+)/', views.share, name="share"),
    path('unshare/(<album_id>[0-9]+)/(<username>[\w\-]+)/', views.unshare, name="unshare"),
]

users/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path,include

from . import views

app_name = 'users'

urlpatterns = [
    # path('index/', views.index, name='index'),
    # path('register/', views.register, name='register'),
    # path('login_user/', views.login_user, name='login_user'),
    # path('logout_user/', views.logout_user, name='logout_user'),
    # path('profile/', views.profile, name="profile"),
    # path('edit_profile/', views.edit_profile, name="edit_profile"),
    # path('update_profile/', views.update_profile, name="update_profile"),
    # path('logout/', views.logout, name="logout"),
    # path('follow_users/', views.follow_users, name="follow_users"),
    # path('follow/(?P<followee_id>\d+)/', views.follow, name="follow"),
    # path('unfollow/(?P<followee_id>\d+)/', views.unfollow, name="unfollow"),
    # path('my_followers/', views.my_followers, name="my_followers"),
    # path('follower_profile/(?P<follower_id>\d+)/', views.follower_profile, name="follower_profile")

    path('index/', views.index, name='index'),
    path('register/', views.register, name='register'),
    path('login_user/', views.login_user, name='login_user'),
    path('logout_user/', views.logout_user, name='logout_user'),
    path('profile/', views.profile, name="profile"),
    path('edit_profile/', views.edit_profile, name="edit_profile"),
    path('update_profile/', views.update_profile, name="update_profile"),
    path('logout/', views.logout, name="logout"),
    path('follow_users/', views.follow_users, name="follow_users"),
    path('follow/(<followee_id>)/', views.follow, name="follow"),
    path('unfollow/(<followee_id>)/', views.unfollow, name="unfollow"),
    path('my_followers/', views.my_followers, name="my_followers"),
    path('follower_profile/(<follower_id>)/', views.follower_profile, name="follower_profile")
]

users/models.py
from __future__ import unicode_literals
#
from django.contrib.auth.models import User
from django.db import models


class Friend(models.Model):
    follower = models.ForeignKey(User, related_name="followees",on_delete=models.CASCADE)
    followee = models.ForeignKey(User, related_name="followers",on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

users/forms.py
from django import forms
from django.contrib.auth.models import User
# from .models import *

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['first_name','last_name','username', 'email', 'password']

users/views.py
from itertools import chain

from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.contrib.auth.models import User
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.db.models import Q

from music.models import Album, Song, Shared_album
from .forms import  UserForm
from .models import Friend



def index(request):
    if not request.user.is_authenticated:
        return render(request, 'users/login.html')
    else:
        followee = Friend.objects.filter(follower=request.user)
        friends_albums = []
        for follo in followee:
            x = Album.objects.filter(Q(user=follo.followee)).exclude(is_private=True)
            friends_albums = chain(friends_albums,x)

        received_albums = Shared_album.objects.filter(receiver__username__exact=request.user.username)
        public_albums = Album.objects.exclude(user=request.user).filter(is_private=False)
        albums = Album.objects.filter(user=request.user)
        song_results = Song.objects.all()
        query = request.GET.get("q")
        if query:
            public_albums_search = public_albums.filter(
                Q(album_title__icontains=query) |
                Q(artist__icontains=query)
            ).distinct()

            own_albums_search = albums.filter(
                Q(album_title__icontains=query) |
                Q(artist__icontains=query)
            ).distinct()

            received_albums_search = received_albums.filter(
                Q(album_title__album_title__icontains=query) |
                Q(album_title__artist__icontains=query)
            ).distinct()

            song_results = song_results.filter(
                Q(song_title__icontains=query)
            ).distinct()

            return render(request, 'users/index.html', {
                'public_albums_search': public_albums_search,
                'received_albums_search' : received_albums_search,
                'own_albums_search': own_albums_search,
                'query':query,
                'songs': song_results,
            })
        else:
            context = {
                'albums': albums , # unique albums
                'received_albums': received_albums,
                'public_albums': public_albums,
                'friends_albums': friends_albums
            }
            return render(request, 'users/index.html', context )

def home(request):
    return render(request,'home.html')

def logout_user(request):
    logout(request)
    form = UserForm(request.POST or None)
    context = {
        "form": form,
    }
    return render(request, 'users/login.html', context)


def login_user(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            request.session['username'] = user.username
            request.session['id'] = user.id
            request.session['first_name'] = user.first_name
            request.session['last_name'] = user.last_name
            request.session['email'] = user.email
            request.session['password'] = user.password
            if user.is_active:
                login(request, user)
                followee = Friend.objects.filter(follower=request.user)
                friends_albums = []
                for follo in followee:
                    x = Album.objects.filter(Q(user=follo.followee)).exclude(is_private=True)
                    friends_albums = chain(friends_albums, x)

                received_albums = Shared_album.objects.filter(receiver=request.user)
                public_albums = Album.objects.exclude(user=request.user).filter(is_private=False)
                albums = Album.objects.filter(user=request.user)
                context = {
                    'albums': albums,  # unique albums
                    'received_albums': received_albums,
                    'public_albums': public_albums,
                    'friends_albums': friends_albums
                }
                return render(request, 'users/index.html', context)
            else:
                return render(request, 'users/login.html', {'error_message': 'Your account has been disabled'})
        else:
            return render(request, 'users/login.html', {'error_message': 'Invalid login'})
    return render(request, 'users/login.html')


def register(request):
    form = UserForm(request.POST or None)
    if form.is_valid():
        user = form.save(commit=False)
        last_name = form.cleaned_data['last_name']
        first_name = form.cleaned_data['first_name']
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user.set_password(password)
        request.session['username'] = user.username
        request.session['id'] = user.id
        request.session['first_name'] = user.first_name
        request.session['last_name'] = user.last_name
        request.session['email'] = user.email
        request.session['password'] = user.password
        user.save()
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                albums = Album.objects.filter(user=request.user)
                return render(request, 'users/index.html', {'albums': albums})
    context = {
        "form": form,
    }
    return render(request, 'users/register.html', context)

def profile(request):
    followee = Friend.objects.filter(follower__username__exact=request.user.username)
    following_count = followee.count()
    friends_albums = []
    for follo in followee:
        x = Album.objects.filter(Q(user=follo.followee)).exclude(is_private=True)
        friends_albums = list(chain(friends_albums, x))

    print(friends_albums)

    received_albums = Shared_album.objects.filter(receiver=request.user)

    public_albums = Album.objects.exclude(user=request.user).filter(is_private=False)
    private_albums = Album.objects.filter(user=request.user,is_private=True)

    #find folowers count
    followers = Friend.objects.filter(followee__username__exact=request.user.username)
    followers_count = followers.count()

    #find shared_albums which are private
    list_of_ids = []
    for pa in private_albums:
        list_of_ids.append(pa.id)

    shared_albums = Shared_album.objects.filter(album_title_id__in=list_of_ids)

    context = {
        'private_albums': private_albums,  # unique albums
        'received_albums': received_albums,
        'public_albums': public_albums,
        'shared_albums':shared_albums,
        'friends_albums': friends_albums,
        'following_count':following_count,
        'followers_count': followers_count
    }
    return render(request, 'users/profile.html', context)


def edit_profile(request):
    return render(request, 'users/edit_profile.html')


def update_profile(request):
    if request.method == "POST":
        server_firstname = request.POST['first_name']
        server_lastname = request.POST['last_name']
        server_password = request.POST['password']
        if server_password == request.POST['confirm_password']:
            try:
                user = User.objects.get(username = request.session['username'])
                user.first_name = server_firstname
                user.last_name = server_lastname
                user.password = server_password
                user.save()
                request.session['first_name'] = user.first_name
                request.session['last_name'] = user.last_name
                request.session['password'] = user.password
                return render(request,'users/profile.html')
            except:
                messages.error(request, 'ERROR: Invalid inputs, try again!')
                return render(request,'users/edit_profile.html')
        else:
            messages.error(request, 'ERROR: Passwords do not match, try again!')
            return render(request,'users/edit_profile.html')
    else:
        messages.error(request, 'ERROR: Invalid inputs, try again!')
        return render(request,'users/edit_profile.html')


def follow_users(request):
    context = {
        "notfriends": User.objects.exclude(id=request.session['id']).exclude(followers__follower_id=request.session['id']),
        "friends": User.objects.filter(followers__follower_id=request.session['id'])
    }
    return render(request, 'users/follow_users.html', context)


def follow(request, followee_id):
    Friend.objects.create(follower_id=request.session['id'], followee_id=followee_id)
    context = {
        "notfriends": User.objects.exclude(id=request.session['id']).exclude(
            followers__follower_id=request.session['id']),
        "friends": User.objects.filter(followers__follower_id=request.session['id'])
    }
    return render(request,'users/follow_users.html',context)


def unfollow(request, followee_id):
    Friend.objects.filter(followee_id=followee_id).delete()
    context = {
        "notfriends": User.objects.exclude(id=request.session['id']).exclude(
            followers__follower_id=request.session['id']),
        "friends": User.objects.filter(followers__follower_id=request.session['id'])
    }
    return render(request,'users/follow_users.html',context)


def my_followers(request):
    context = {
        "my_followers": Friend.objects.filter(followee__id=request.session['id'])
        }
    return render(request, 'users/my_followers.html', context)


def follower_profile(request, follower_id):
    context = {
        "friend": Friend.objects.get(id=follower_id)
    }
    return render(request, 'users/follower_profile.html', context)

templates/users/edit_profile.html
{% extends 'base.html' %}
{% block title %}Log In{% endblock %}
{% block login_active %}active{% endblock %}

{% block body %}
 <br><br>
<div class="row">
  <div class="col-sm-12 col-md-6">
      <div class="panel panel-default">
          <div class="panel-body">
            
            <h3>Edit Your Profile</h3>
            <a href="{% url 'users:profile' %}">Back to Profile</a>
            <hr>
            {% for m in messages %}
              <p>{{m}}</p>
            {% endfor %}
            <br>
              <form action="{% url 'users:update_profile' %}" method="post">
                {% csrf_token %}
                First Name: <input type="text" name="first_name" placeholder="{{request.session.first_name}}"><br><br>
                Last Name: <input type="text" name="last_name" placeholder="{{request.session.last_name}}"><br><br>
                Password: <input type="password" name="password"><br><br>
                Confirm Password: <input type="password" name="confirm_password"><br><br>
                <input style="margin:10px; font-size:13pt;" type="submit" name="edit" value="Update Profile">
              </form>           
          </div>
      </div>
  </div>
</div>

</div>
  
{% endblock %}

templates/users/follow_users.html
{% extends 'base.html' %}
{% block title %}Log In{% endblock %}
{% block login_active %}active{% endblock %}

{% block body %}
 <br><br>
<div class="container-fluid">

  <div class="row">
      <div class="col-sm-12 col-md-6">
          <div class="panel panel-default">
              <div class="panel-body">
                <h3>Follow Users</h3>
                  {% for notfriend in notfriends %}
                  <ul>
                    <li>{{notfriend.first_name}} {{notfriend.last_name}}&nbsp;&nbsp;&nbsp;&nbsp;<a href="{% url 'users:follow' followee_id=notfriend.id %}">Follow</a></li>
                  </ul>
                  {% endfor %}
                <hr>
                  <h3>Unfollow Users</h3>
                  {% for friend in friends %}
                  <ul>
                    <li>{{friend.first_name}} {{friend.last_name}}&nbsp;&nbsp;&nbsp;&nbsp;<a href="{% url 'users:unfollow' followee_id=friend.id %}">Unfollow</a></li>
                  </ul>
                {% endfor %}
              </div>
          </div>
      </div>
  </div>

</div>
  

{% endblock %}

templates/users/follower_profile.html
{% extends 'base.html' %}
{% block title %}Log In{% endblock %}
{% block login_active %}active{% endblock %}

{% block body %}

 <br><br>
  <div class="row">
      <div class="col-sm-12 col-md-6">
          <div class="panel panel-default">
              <div class="panel-body">
               
                <h3>{{friend.follower.first_name}}'s Profile</h3>
                <a href="{% url 'users:my_followers' %}">Back to My Followers</a>&nbsp;&nbsp;&nbsp;&nbsp;
                <a href="{% url 'users:index' %}">Home</a><br>
                <hr>
                <p>
                  <b>Username:</b> {{friend.follower.username}} <br><br>
                  <b>First Name:</b> {{friend.follower.first_name}} <br><br>
                  <b>Last Name:</b> {{friend.follower.last_name}} <br><br>
                  <b>Email:</b> {{friend.follower.email}} <br><br>
                </p>
              </div>
          </div>
      </div>
  </div>

</div>
  
{% endblock %}

templates/users/login.html
{% extends 'base_visitor2.html' %}
{% block title %}Log In{% endblock %}
{% block login_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">
 <br>
    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Log In</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="{% url 'users:login_user'%}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_username">
                                Username:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_username" maxlength="30" name="username" type="text">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_password">
                                Password:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_password" maxlength="30" name="password" type="password">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                                &nbsp;&nbsp;&nbsp;
                                <a href="{% url 'password_reset' %}">Forgot Password?</a>
                            </div>
                            
                        </div>
                    </form>
                </div>
                <div class="panel-footer">
                    Don't have an account? <a href="{% url 'users:register' %}">Click here</a> to register.
                </div>
            </div>
        </div>
    </div>

</div>

{% endblock %}

templates/users/logout.html
{% extends "base_visitor2.html" %}
{% block content %}
     <br>
    <h2>You have been logged out</h2>
    <div class="border-top pt-3">
        <small class="text-muted">
            <a href="{% url 'login' %}">Log In Again</a>
        </small>
    </div>
{% endblock content %}

templates/users/my_followers.html
{% extends 'base.html' %}
{% block title %}Log In{% endblock %}
{% block login_active %}active{% endblock %}

{% block body %}
     <br><br>
<div class="container-fluid">

    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>My Followers
                    <a href="{% url 'users:index' %}">&emsp13;&emsp14;&emsp14;Home</h3></a>
                    <hr>
                    {% for follower in my_followers %}
                        <ul>
                            <li>{{ follower.follower.first_name }} {{ follower.follower.last_name }}&nbsp;<a
                                    href="{% url 'users:follower_profile' follower_id=follower.id %}">View Profile</a>
                            </li>
                        </ul>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>

</div>
{% endblock %}

templates/users/password_reset.html
{% extends "base_visitor.html" %}
{% load crispy_forms_tags %}
{% block content %}
     <br>
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Reset Password</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Request Password Reset</button>
            </div>
        </form>
    </div>
{% endblock content %}

templates/users/password_reset_complete.html
{% extends "base_visitor.html" %}
{% block content %}
     <br><br>
    <div class="alert alert-info">
        Your password has been set.
    </div>
    <a href="{% url 'users:login_user' %}">Sign In Here</a>
{% endblock content %}

templates/users/profile.html
{% extends 'base.html' %}
{% block title %}Log In{% endblock %}
{% block login_active %}active{% endblock %}

{% block body %}
     <br><br>

    <div class="container-fluid">

        <div class="row">
            <div class="col-sm-12 col-md-6">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <h3>{{ request.session.username }}'s Profile</h3>
                        <a href="{% url 'users:edit_profile' %}">Edit Profile</a>&nbsp;&nbsp;&nbsp;&nbsp;
                        <a href="{% url 'users:index' %}">Home</a>
                        <hr>
                        <br>
                        <p>
                            <b>First Name:</b> {{ request.session.first_name }}<br><br>
                            <b>Last Name:</b> {{ request.session.last_name }} <br><br>
                            <b>Email:</b> {{ request.session.email }} <br><br>
                            <b>Followers:</b> {{ followers_count }} <br><br>
                            <b>Following:</b> {{ following_count }} <br><br>
                        </p>
                    </div>
                </div>
            </div>
        </div>

        {# User's Activity on Site #}
        <div class="row">
            <div class="col-sm-12 col-md-6">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <h3>{{ request.session.username }}'s Activity</h3>&nbsp;
                        <a href="{% url 'users:index' %}">Home</a>
                        <a href="{% url 'users:my_followers' %}">&emsp14;&emsp14;&emsp14;My Followers</a>
                        <hr>
                        <table class="table">
                            <tbody>

                            {#                            private album section#}
                            <tr>
                                <td colspan="2"><h4>Private Albums : {{ private_albums | length }} <br></h4></td>
                            </tr>

                            <tr>
                                {% for album in private_albums %}
                                    <td><h5>{{ album.album_title }} :- <br></h5></td>
                                    {% ifequal album.total_songs null %}
                                        <td><h5> 0 song(s) <br></h5></td>
                                    {% else %}
                                        <td><h5>{{ album.total_songs }} song(s) <br></h5></td>
                                    {% endifequal %}
                                {% endfor %}
                            </tr>

                            {#                            Public album section#}
                            <tr>
                                <td colspan="2"><h4>Public Albums : {{ public_albums | length }} <br></h4></td>
                            </tr>

                            <tr>
                                {% for album in public_albums %}
                                    <td><h5>{{ album.album_title }} :- <br></h5></td>
                                    {% ifequal album.total_songs null %}
                                        <td><h5> 0 song(s) <br></h5></td>
                                    {% else %}
                                        <td><h5>{{ album.total_songs }} song(s) <br></h5></td>
                                    {% endifequal %}
                                {% endfor %}
                            </tr>


                            {#                             Shared Album section#}
                            <tr>
                                <td colspan="2"><h4>Shared Albums : {{ shared_albums | length }} <br></h4></td>
                            </tr>

                            <tr>
                                {% for album in shared_albums %}
                                    <td><h5>{{ album.album_title }} :- <br></h5></td>
                                    {% ifequal album.total_songs null %}
                                        <td><h5> 0 song(s) <br></h5></td>
                                    {% else %}
                                        <td><h5>{{ album.total_songs }} song(s) <br></h5></td>
                                    {% endifequal %}
                                {% endfor %}
                            </tr>

                            {#                            Received Albums#}
                            <tr>
                                <td colspan="2"><h4>Received Albums : {{ shared_albums | length }} <br></h4></td>
                            </tr>

                            <tr>
                                {% for album in received_albums %}
                                    <td><h5>{{ album.album_title }} :- <br></h5></td>
                                    {% ifequal album.total_songs null %}
                                        <td><h5> 0 song(s) <br></h5></td>
                                    {% else %}
                                        <td><h5>{{ album.total_songs }} song(s) <br></h5></td>
                                    {% endifequal %}
                                {% endfor %}
                            </tr>

                            {#                            Friends Albums#}
                            <tr>
                                <td colspan="2"><h4>Friends Albums : {{ friends_albums | length }} <br></h4></td>
                            </tr>

                            <tr>
                                {% for album in friends_albums %}
                                    <td><h5>{{ album.album_title }} :- <br></h5></td>
                                    {% ifequal album.total_songs null %}
                                        <td><h5> 0 song(s) <br></h5></td>
                                    {% else %}
                                        <td><h5>{{ album.total_songs }} song(s) <br></h5></td>
                                    {% endifequal %}
                                {% endfor %}
                            </tr>

                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/users/register.html
{% extends 'base_visitor2.html' %}
{% block title %}Register{% endblock %}
{% block register_active %}active{% endblock %}

{% block body %}
     <br><br>
<div class="container-fluid">

    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Register for an Account</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'music/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="panel-footer">
                    Already have an account? <a href="{% url 'users:login_user' %}">Click here</a> to log in.
                </div>
            </div>
        </div>
    </div>

</div>

{% endblock %}